# Project team members listed below will appear on the /team page

- title: Geocomputation with R
  authors: 
    - Robin Lovelace
    - Jakub Nowosad
    - Jannes Muenchow
  image: /assets/img/training_geocomputation.png
  description: > # Can be Markdown
    This book is for people who want to analyze, visualize and model geographic data with open source software. It is based on R, a statistical programming language that has powerful data processing, visualization and geospatial capabilities. The book covers a wide range of topics and will be of interest to a wide range of people from many different backgrounds.
  link: https://geocompr.robinlovelace.net/
  license: /assets/license_cc-by-nc-nd.png
  license_link: https://creativecommons.org/licenses/by-nc-nd/4.0/ 

- title: Geospatial Health Data - Modeling and Visualization with R-INLA and Shiny
  authors: Paula Moraga
  image: /assets/img/training_inla.jpg
  description: >
    The book describes spatial and spatio-temporal statistical methods and visualization techniques to analyze georeferenced health data in R.
    Examples in the book focus on health applications, but the approaches covered are also applicable to other fields that use georeferenced data.
  link: http://www.paulamoraga.com/book-geospatial/
  license: /assets/license_cc-by-nc-nd.png
  license_link: https://creativecommons.org/licenses/by-nc-nd/4.0/

